// <auto-generated />
using System;
using AlgoJudge.Server.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlgoJudge.Server.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260803225009_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasQuestions")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasRanking")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasRules")
                        .HasColumnType("boolean");

                    b.Property<int>("JoinPolicy")
                        .HasColumnType("integer");

                    b.Property<int>("LogVisibility")
                        .HasColumnType("integer");

                    b.Property<int>("MaxAttachments")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxSubmissionsPerProblem")
                        .HasColumnType("integer");

                    b.Property<long>("MaxUploadBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RankingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RulesFileId")
                        .HasColumnType("uuid");

                    b.Property<int>("ScoreVisibility")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RulesFileId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Activities", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.EvaluationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProblemVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RunnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProblemVersionId");

                    b.HasIndex("RunnerId");

                    b.HasIndex("State", "CreatedAt");

                    b.HasIndex("SubmissionId", "Attempt")
                        .IsUnique();

                    b.ToTable("EvaluationJobs", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProblemVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProblemVersionId");

                    b.HasIndex("Sha256");

                    b.HasIndex("SubmissionId");

                    b.ToTable("Files", null, t =>
                        {
                            t.HasCheckConstraint("CK_Files_SingleOwner", "num_nonnulls(\"ProblemVersionId\", \"SubmissionId\") <= 1");
                        });
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Grant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedFromTemplate")
                        .HasColumnType("text");

                    b.Property<string>("GrantedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"ActivityId\" IS NULL");

                    b.HasIndex("ActivityId", "State");

                    b.HasIndex("UserId", "ActivityId")
                        .IsUnique()
                        .HasFilter("\"ActivityId\" IS NOT NULL");

                    b.ToTable("Grants", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.PermissionTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PermissionTemplates", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Problem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SharedWith")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("OwnerUserId", "Visibility");

                    b.ToTable("Problems", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.ProblemVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ProblemId", "Version")
                        .IsUnique();

                    b.ToTable("ProblemVersions", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerAuthorUserId")
                        .HasColumnType("text");

                    b.Property<string>("AnswerBody")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AuthorUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SeriesProblemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("SeriesProblemId");

                    b.HasIndex("ActivityId", "CreatedAt");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.QuestionRead", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("QuestionId", "UserId");

                    b.ToTable("QuestionReads", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Result", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("EvaluationJobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Log")
                        .HasColumnType("text");

                    b.Property<double?>("MaxScore")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ProblemVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RunnerVersion")
                        .HasColumnType("text");

                    b.Property<double?>("Score")
                        .HasColumnType("double precision");

                    b.Property<string>("Verdict")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationJobId")
                        .IsUnique();

                    b.ToTable("Results", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Runner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Capabilities")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.ToTable("Runners", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RankingFreezeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RankingRevealAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RevealProblemCount")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId", "Slug")
                        .IsUnique();

                    b.ToTable("Series", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.SeriesProblem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("MaxAttachments")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxSubmissions")
                        .HasColumnType("integer");

                    b.Property<long?>("MaxUploadBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PinnedProblemVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("PinnedProblemVersionId");

                    b.HasIndex("ProblemId");

                    b.HasIndex("SeriesId", "Slug")
                        .IsUnique();

                    b.ToTable("SeriesProblems", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<Guid>("SeriesProblemId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("SeriesProblemId", "UserId");

                    b.ToTable("Submissions", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Activity", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.File", "RulesFile")
                        .WithMany()
                        .HasForeignKey("RulesFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RulesFile");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.EvaluationJob", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.ProblemVersion", "ProblemVersion")
                        .WithMany()
                        .HasForeignKey("ProblemVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlgoJudge.Server.Database.Models.Runner", "Runner")
                        .WithMany("Jobs")
                        .HasForeignKey("RunnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AlgoJudge.Server.Database.Models.Submission", "Submission")
                        .WithMany("Jobs")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProblemVersion");

                    b.Navigation("Runner");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.File", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.ProblemVersion", "ProblemVersion")
                        .WithMany("Files")
                        .HasForeignKey("ProblemVersionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AlgoJudge.Server.Database.Models.Submission", "Submission")
                        .WithMany("Files")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ProblemVersion");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Grant", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.Activity", "Activity")
                        .WithMany("Grants")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AlgoJudge.Server.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Problem", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.ProblemVersion", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AlgoJudge.Server.Database.Models.Problem", "Problem")
                        .WithMany("Versions")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Question", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.Activity", "Activity")
                        .WithMany("Questions")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlgoJudge.Server.Database.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlgoJudge.Server.Database.Models.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AlgoJudge.Server.Database.Models.SeriesProblem", "SeriesProblem")
                        .WithMany("Questions")
                        .HasForeignKey("SeriesProblemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Activity");

                    b.Navigation("Author");

                    b.Navigation("Series");

                    b.Navigation("SeriesProblem");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.QuestionRead", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.Question", "Question")
                        .WithMany("Reads")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Result", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.EvaluationJob", "EvaluationJob")
                        .WithOne("Result")
                        .HasForeignKey("AlgoJudge.Server.Database.Models.Result", "EvaluationJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluationJob");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Series", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.Activity", "Activity")
                        .WithMany("Series")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.SeriesProblem", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.ProblemVersion", "PinnedProblemVersion")
                        .WithMany()
                        .HasForeignKey("PinnedProblemVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlgoJudge.Server.Database.Models.Problem", "Problem")
                        .WithMany("SeriesProblems")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlgoJudge.Server.Database.Models.Series", "Series")
                        .WithMany("SeriesProblems")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PinnedProblemVersion");

                    b.Navigation("Problem");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Submission", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.SeriesProblem", "SeriesProblem")
                        .WithMany("Submissions")
                        .HasForeignKey("SeriesProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlgoJudge.Server.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SeriesProblem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlgoJudge.Server.Database.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AlgoJudge.Server.Database.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Activity", b =>
                {
                    b.Navigation("Grants");

                    b.Navigation("Questions");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.EvaluationJob", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Problem", b =>
                {
                    b.Navigation("SeriesProblems");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.ProblemVersion", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Question", b =>
                {
                    b.Navigation("Reads");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Runner", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Series", b =>
                {
                    b.Navigation("SeriesProblems");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.SeriesProblem", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("AlgoJudge.Server.Database.Models.Submission", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
